@api =  http://localhost:4000/categorys

GET {{api}}

################################

POST {{api}}
Content-Type: application/json

{
    "Category" :"Ejemplo s"
}
################################
GET {{api}}/10
################################
DELETE {{api}}/10
################################
GET {{api}}/count
################################
PUT {{api}}/14
Content-Type: application/json

{
    "Category" :"Prueba Update"
}
################################