@api = http://localhost:4000/funding

GET {{api}}/rank
################################
POST {{api}}
Content-Type: application/json

{
    "Title" :"Ejemplo",
    "Question1" :"Ejemplo",
    "Question2" :"Ejemplo",
    "Question3" :"Ejemplo",
    "FastDescription" :"Ejemplo",
    "Description" :"Ejemplo",
    "FundingImage1" :"Ejemplo",
    "FundingImage2" :"Ejemplo",
    "FundingImage3" :"Ejemplo",
    "FundingVideo" :"Ejemplo",
    "AccountNumber" :"Ejemplo",
    "SocialMedia" :"Ejemplo",
    "IdCategory" : 1,
    "Goal" :10000.00
}
################################